### ISSUE TITLE
Question on the JWE from pem

### ISSUE THREAD

**Issue by DementedEarplug** [plataux/webcrypt#3]
I don t know if I'm being stupid, but I cant seem to recover a JWE from a pem file. THis is a simplified version of what I'm trying to do:

```python
>>> jwe = JWE(algorithm=JWE.Algorithm.RSA1_5, encryption=JWE.Encryption.A256GCM)
>>> pem = jwe.to_pem()
>>> newJwe = JWE.from_pem(pem)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".local/share/virtualenvs/aph-1RMFTx5R/lib/python3.10/site-packages/webcrypt/jwe.py", line 900, in from_pem
    return cls(algorithm, encryption, priv_key, kid)
  File ".local/share/virtualenvs/aph-1RMFTx5R/lib/python3.10/site-packages/webcrypt/jwe.py", line 656, in __init__
    raise ValueError("Unknown JWE Algorithm or invalid key type")
ValueError: Unknown JWE Algorithm or invalid key type
```

I guess my question is how exactly does the `from_pem` method work. And is there an API documentation for the webcrypt library?

**Comment by DementedEarplug** [comment]
I was being stupid, I was not passing down the algorithm.
